services:
  db:
    image: postgres:16
    container_name: postgres_container
    environment:
      POSTGRES_USER: admintest
      POSTGRES_PASSWORD: adminpasswordtest
      POSTGRES_DB: bingodbtest
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bingo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d bingodbtest -U admintest"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: .
      target: builder
    command: npm run test:docker
    container_name: bingo-backend
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://admintest:adminpasswordtest@postgres_container:5432/bingodbtest?schema=public
    networks:
      - bingo-network
networks:
  bingo-network:
    driver: bridge

volumes:
  pgdata: