services:
  db:
    image: postgres:16
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: bingodb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bingo-network
  backend:
    build: .
    container_name: bingo-backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - bingo-network


networks:
  bingo-network:

volumes:
  pgdata: